spring.application.name=server
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/api_proxy
spring.r2dbc.username=${PROXY_DB_USERNAME}
spring.r2dbc.password=${PROXY_DB_PASSWORD}

spring.sql.init.mode=always
spring.sql.init.platform=postgres
logging.level.org.springframework.r2dbc=DEBUG